### ISSUE TITLE
Error: Cannot find module 'ascii-art-ansi/color'

### ISSUE THREAD

**Issue by thiagovilla** [khrome/ascii-art-image#1]
Replicate error:

1. `mkdir test && cd test`
2. `npm i ascii-art-image`
3. `code index.js`

```JS
// index.js
var Image = require('ascii-art-image')

;(function () {
  var filepath = './image.png'
  var alphabet = 'variant1'
  var image = new Image({ filepath, alphabet })
  image.write(function (err, rendered) {
    console.log(rendered)
  })
})()
```

4. `node index.js`

```
internal/modules/cjs/loader.js:775
    throw err;
    ^

Error: Cannot find module 'ascii-art-ansi/color'
Require stack:
- /media/thiago/HDD/Projetos/ascii-art-image-test/node_modules/ascii-art-image/image.js
- /media/thiago/HDD/Projetos/ascii-art-image-test/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:772:15)
    at Function.Module._load (internal/modules/cjs/loader.js:677:27)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at /media/thiago/HDD/Projetos/ascii-art-image-test/node_modules/ascii-art-image/image.js:44:13
    at Object.<anonymous> (/media/thiago/HDD/Projetos/ascii-art-image-test/node_modules/ascii-art-image/image.js:61:2)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/media/thiago/HDD/Projetos/ascii-art-image-test/node_modules/ascii-art-image/image.js',
    '/media/thiago/HDD/Projetos/ascii-art-image-test/index.js'
  ]
}
```

**Comment by khrome** [comment]
You aren't including it in your bundler: https://www.npmjs.com/package/cjs-loader (`ascii-art-ansi` is a peer dependency of ascii-art-image, and must be manually imported, you should be getting a warning in your console on install)

**Comment by khrome** [comment]
furthermore all these classes are already AMD bundled, so you're attempting to rewrap them in AMD. It won't cause errors, but is maybe.. not fruitful?

Also, you may want to check this loader, at the top of the readme you'll see: `This is an interesting, successful but terrible idea and should not be used by anyone. It reqiures support for ES6 Modules 🛠️ and has only really been tested on Chrome 61+`, and hasn't had a publish in 2 years... so I'd expect a rocky road.
